import React, { useEffect } from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import ParticleBackground from '../components/ParticleBackground';

// Re-using the same prose styles from the Privacy Policy for consistency
const proseStyles = `
.prose-custom {
    color: #cbd5e1; /* slate-300 */
}
.prose-custom a {
    color: #60a5fa; /* blue-400 */
    text-decoration: none;
    transition: color 0.2s;
}
.prose-custom a:hover {
    color: #93c5fd; /* blue-300 */
}
.prose-custom h1, .prose-custom h2, .prose-custom h3 {
    color: #f8fafc; /* slate-50 */
}
.prose-custom strong {
    color: #f1f5f9; /* slate-100 */
}
.prose-custom ul > li::marker {
    color: #60a5fa; /* blue-400 */
}
`;

const TermsAndConditions: React.FC = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <>
    <style>{proseStyles}</style>
    <div className="bg-slate-950 text-white font-sans animate-content-fade-in">
      <ParticleBackground />
      <Header />
      
      <main id="top" className="relative z-10 pt-24">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <div className="max-w-4xl mx-auto">
            <h1 className="text-4xl sm:text-5xl font-extrabold text-white text-center mb-8">
              Terms & <span className="text-blue-400">Conditions</span>
            </h1>
            <div className="prose-custom bg-slate-900/50 border border-slate-800 rounded-lg p-6 md:p-10 leading-relaxed">
              <p><strong>Last Updated:</strong> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

              <h2>1. Agreement to Terms</h2>
              <p>By accessing and using the Prevaledge website (the "Site") and its services, including the AI Toolkit, you agree to be bound by these Terms and Conditions. If you do not agree with all of these terms, you are prohibited from using the Site and must discontinue use immediately.</p>

              <h2>2. Intellectual Property Rights</h2>
              <p>Unless otherwise indicated, the Site is our proprietary property. All source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Site (collectively, the "Content") and the trademarks and logos contained therein are owned or controlled by us and are protected by copyright and trademark laws. The Content is provided on the Site "AS IS" for your information and personal use only.</p>
              
              <h2>3. Use of AI Toolkit</h2>
              <p>Our Site offers a suite of free AI-powered tools (the "AI Toolkit") for your use. In using these tools, you agree to the following:</p>
              <ul>
                <li>The tools are provided for informational and illustrative purposes. The outputs generated by the AI are not guaranteed to be accurate, complete, or suitable for any specific purpose.</li>
                <li>You are solely responsible for the inputs you provide and for how you use the generated outputs.</li>
                <li>You agree not to use the AI Toolkit for any illegal, harmful, or malicious activities.</li>
                <li>We reserve the right to modify, suspend, or discontinue any tool at any time without notice.</li>
              </ul>

              <h2>4. Prohibited Activities</h2>
              <p>You may not access or use the Site for any purpose other than that for which we make the Site available. The Site may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us. Prohibited activity includes, but is not limited to, unauthorized use of the Site, engaging in any automated use of the system, or attempting to bypass any measures of the Site designed to prevent or restrict access.</p>

              <h2>5. Disclaimer</h2>
              <p>The Site and its services are provided on an "as-is" and "as-available" basis. You agree that your use of the Site and our services will be at your sole risk. To the fullest extent permitted by law, we disclaim all warranties, express or implied, in connection with the site and your use thereof, including, without limitation, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement.</p>

              <h2>6. Limitations of Liability</h2>
              <p>In no event will we or our directors, employees, or agents be liable to you or any third party for any direct, indirect, consequential, exemplary, incidental, special, or punitive damages, including lost profit, lost revenue, loss of data, or other damages arising from your use of the site, even if we have been advised of the possibility of such damages.</p>
              
              <h2>7. Governing Law</h2>
              <p>These Terms and Conditions and your use of the Site are governed by and construed in accordance with the laws of India, applicable to agreements made and to be entirely performed within India, without regard to its conflict of law principles.</p>

              <h2>8. Contact Us</h2>
              <p>To resolve a complaint regarding the Site or to receive further information regarding use of the Site, please contact us at:</p>
              <p>
                Prevaledge<br />
                C 1 To 26 Vardhman Grandeur, Andheri West<br />
                Mumbai, India 400058<br />
                Email: info@prevaledge.com
              </p>
            </div>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
    </>
  );
};

export default TermsAndConditions;
